<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ItemDataLibrary\ItemDataLibrary.csproj" />
    <ProjectReference Include="..\ITS152L-Project\ITS152L-Project.csproj" />
  </ItemGroup>

</Project>