// <auto-generated />
using ITS152L_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITS152L_Project.Migrations
{
    [DbContext(typeof(ItemApiContext))]
    [Migration("20250920101225_item data added")]
    partial class itemdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItemDataLibrary.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Penguin",
                            Code = 1001,
                            Name = "Book",
                            Quantity = 10,
                            UnitPrice = 10.5
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Safegaurd",
                            Code = 1002,
                            Name = "Soap",
                            Quantity = 10,
                            UnitPrice = 12.5
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Clear",
                            Code = 1003,
                            Name = "Shampoo",
                            Quantity = 10,
                            UnitPrice = 8.5
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Durex",
                            Code = 1004,
                            Name = "Condom",
                            Quantity = 10,
                            UnitPrice = 6.5
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Logitech",
                            Code = 1005,
                            Name = "Mouse",
                            Quantity = 10,
                            UnitPrice = 20.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
