@rootURL = http://localhost:5111

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/item
Accept: application/JSON

###
GET {{rootURL}}/api/item/2
Accept: application/JSON

###
POST {{rootURL}}/api/item
Content-Type: application/JSON 
{

    "name": "Food",
    "code": 1006,
    "brand": "Oishi",
    "unitPrice": 5.12,
    "quantity": 15

}

###
PUT {{rootURL}}/api/item/5
Content-Type: application/JSON
{
    "id": 5,
    "name": "Mouse",
    "code": 1005,
    "brand": "Razer",
    "unitPrice": 22.5,
    "quantity": 25
}

###

DELETE {{rootURL}}/api/item/6


###

DELETE {{rootURL}}/api/item

###

GET {{rootURL}}/api/user
Accept: application/JSON

###
GET {{rootURL}}/api/user/2
Accept: application/JSON

###
POST {{rootURL}}/api/user
Content-Type: application/JSON 
{

    "userName": "SHSHunter",
    "firstName": "Juoross Phillip",
    "lastName": "Jose",
    "password": "12345678"

}

###
POST {{rootURL}}/api/user
Content-Type: application/JSON 
{

    "userName": "BarneyBoy",
    "firstName": "Ken",
    "lastName": "Aliling",
    "password": "ManoosLover69"

}

###
PUT {{rootURL}}/api/user/2
Content-Type: application/JSON 
{
    "id": "2",
    "userName": "BarneyKid",
    "firstName": "Ken",
    "lastName": "Aliling",
    "password": "ManoosLover69"

}


###
DELETE {{rootURL}}/api/user/3

###
DELETE {{rootURL}}/api/user

###
POST {{rootURL}}/api/login
Content-Type: application/JSON 
{

    "userName": "SHSHunter",
    "password": "12345678"

}